CREATE DATABASE SORTEIO_PY
USE SORTEIO_PY

CREATE TABLE PARTICIPANTE (
	COD_PARTICIPANTE INT IDENTITY NOT NULL,
	NUM_PARTICIPANTE VARCHAR (50) NOT NULL,
    NOME_PARTICIPANTE VARCHAR(50) NOT NULL 
)

INSERT INTO NUMEROS (NUM_PARTICIPANTE, NOME_PARTICIPANTE) VALUES ('74 96152-2364','Pedro') 

CREATE PROCEDURE SP_NUMSORTEADO @IDSORTEADO INT AS SELECT * FROM NUMEROS WHERE COD_PARTICIPANTE = @IDSORTEADO;
EXEC SP_NUMSORTEADO 6